spring.application.name=employeeApp

# ===============================
# DATABASE CONFIGURATION
# ===============================

spring.datasource.url=jdbc:postgresql://localhost:5432/empcruddb
spring.datasource.username=postgres
spring.datasource.password=lilly@2808

# ===============================
# JPA / HIBERNATE CONFIG
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Optional
#server.port=8080
