spring.application.name=employee-rest-test

spring.datasource.url=jdbc:postgresql://localhost:5432/resttestdb
spring.datasource.username=postgres
spring.datasource.password=lilly@2808

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false