spring.application.name=springbootCRUD

spring.datasource.url=jdbc:postgresql://localhost:5432/cruddb
spring.datasource.username=postgres
spring.datasource.password=lilly@2808

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect